// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethpandaops/contributoor/internal/events (interfaces: BeaconDataProvider)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/beacon_data_provider.mock.go github.com/ethpandaops/contributoor/internal/events BeaconDataProvider
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	phase0 "github.com/attestantio/go-eth2-client/spec/phase0"
	beacon "github.com/ethpandaops/beacon/pkg/beacon"
	ethwallclock "github.com/ethpandaops/ethwallclock"
	gomock "go.uber.org/mock/gomock"
)

// MockBeaconDataProvider is a mock of BeaconDataProvider interface.
type MockBeaconDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockBeaconDataProviderMockRecorder
}

// MockBeaconDataProviderMockRecorder is the mock recorder for MockBeaconDataProvider.
type MockBeaconDataProviderMockRecorder struct {
	mock *MockBeaconDataProvider
}

// NewMockBeaconDataProvider creates a new mock instance.
func NewMockBeaconDataProvider(ctrl *gomock.Controller) *MockBeaconDataProvider {
	mock := &MockBeaconDataProvider{ctrl: ctrl}
	mock.recorder = &MockBeaconDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeaconDataProvider) EXPECT() *MockBeaconDataProviderMockRecorder {
	return m.recorder
}

// GetEpoch mocks base method.
func (m *MockBeaconDataProvider) GetEpoch(arg0 uint64) ethwallclock.Epoch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpoch", arg0)
	ret0, _ := ret[0].(ethwallclock.Epoch)
	return ret0
}

// GetEpoch indicates an expected call of GetEpoch.
func (mr *MockBeaconDataProviderMockRecorder) GetEpoch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpoch", reflect.TypeOf((*MockBeaconDataProvider)(nil).GetEpoch), arg0)
}

// GetEpochFromSlot mocks base method.
func (m *MockBeaconDataProvider) GetEpochFromSlot(arg0 uint64) ethwallclock.Epoch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochFromSlot", arg0)
	ret0, _ := ret[0].(ethwallclock.Epoch)
	return ret0
}

// GetEpochFromSlot indicates an expected call of GetEpochFromSlot.
func (mr *MockBeaconDataProviderMockRecorder) GetEpochFromSlot(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochFromSlot", reflect.TypeOf((*MockBeaconDataProvider)(nil).GetEpochFromSlot), arg0)
}

// GetSlot mocks base method.
func (m *MockBeaconDataProvider) GetSlot(arg0 uint64) ethwallclock.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlot", arg0)
	ret0, _ := ret[0].(ethwallclock.Slot)
	return ret0
}

// GetSlot indicates an expected call of GetSlot.
func (mr *MockBeaconDataProviderMockRecorder) GetSlot(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlot", reflect.TypeOf((*MockBeaconDataProvider)(nil).GetSlot), arg0)
}

// GetValidatorIndex mocks base method.
func (m *MockBeaconDataProvider) GetValidatorIndex(arg0 phase0.Epoch, arg1 phase0.Slot, arg2 phase0.CommitteeIndex, arg3 uint64) (phase0.ValidatorIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorIndex", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(phase0.ValidatorIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorIndex indicates an expected call of GetValidatorIndex.
func (mr *MockBeaconDataProviderMockRecorder) GetValidatorIndex(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorIndex", reflect.TypeOf((*MockBeaconDataProvider)(nil).GetValidatorIndex), arg0, arg1, arg2, arg3)
}

// GetWallclock mocks base method.
func (m *MockBeaconDataProvider) GetWallclock() *ethwallclock.EthereumBeaconChain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallclock")
	ret0, _ := ret[0].(*ethwallclock.EthereumBeaconChain)
	return ret0
}

// GetWallclock indicates an expected call of GetWallclock.
func (mr *MockBeaconDataProviderMockRecorder) GetWallclock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallclock", reflect.TypeOf((*MockBeaconDataProvider)(nil).GetWallclock))
}

// Node mocks base method.
func (m *MockBeaconDataProvider) Node() beacon.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Node")
	ret0, _ := ret[0].(beacon.Node)
	return ret0
}

// Node indicates an expected call of Node.
func (mr *MockBeaconDataProviderMockRecorder) Node() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Node", reflect.TypeOf((*MockBeaconDataProvider)(nil).Node))
}

// Synced mocks base method.
func (m *MockBeaconDataProvider) Synced(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synced", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Synced indicates an expected call of Synced.
func (mr *MockBeaconDataProviderMockRecorder) Synced(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synced", reflect.TypeOf((*MockBeaconDataProvider)(nil).Synced), arg0)
}
