project_name: contributoor

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/sentry
    binary: sentry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ethpandaops/contributoor/internal/contributoor.Release={{.Tag}} -X github.com/ethpandaops/contributoor/internal/contributoor.GitCommit={{.ShortCommit}} -X github.com/ethpandaops/contributoor/internal/contributoor.GOOS={{.Os}} -X github.com/ethpandaops/contributoor/internal/contributoor.GOARCH={{.Arch}}
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ethpandaops/contributoor:{{ .Version }}-amd64"
      - "ethpandaops/contributoor:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - go.mod
      - go.sum

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "ethpandaops/contributoor:{{ .Version }}-arm64v8"
      - "ethpandaops/contributoor:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - go.mod
      - go.sum

docker_manifests:
  - name_template: ethpandaops/contributoor:{{ .Version }}
    image_templates:
      - ethpandaops/contributoor:{{ .Version }}-amd64
      - ethpandaops/contributoor:{{ .Version }}-arm64v8
  - name_template: ethpandaops/contributoor:latest
    image_templates:
      - ethpandaops/contributoor:latest-amd64
      - ethpandaops/contributoor:latest-arm64v8

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
